# ==============================================================
# FibraNet ISP — Redirección HTTP → HTTPS
# ==============================================================

server {
    listen 80;
    listen [::]:80;
    server_name _;

    # Certbot ACME challenge (Let's Encrypt)
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
        allow all;
    }

    # Todo lo demás → HTTPS
    location / {
        return 301 https://$host$request_uri;
    }
}
